FROM node:22-alpine

WORKDIR /app


COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./package.json ./package.json

COPY ./packages ./packages
COPY ./apps/http-server ./apps/http-server

RUN npm i -g pnpm
RUN pnpm install

RUN pnpm run generate:client
RUN pnpm run build

EXPOSE 4000

CMD [ "pnpm", "run", "start:http-server" ]


