FROM node:22-alpine

WORKDIR /app


COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json

COPY ./package.json ./package.json

COPY ./packages ./packages
RUN rm -rf ./packages/db
RUN rm -rf ./packages/backend-common
COPY ./apps/fe ./apps/fe

RUN npm i -g pnpm
RUN pnpm install

RUN pnpm run build

EXPOSE 4000

CMD [ "pnpm", "run", "start:fe" ]


